[package]
name = "gamecube_uat_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
websocket = "0.27"

[target.'cfg(windows)'.dependencies]
dolphin-memory = "0.2"
