name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            name: 'Linux'
            version: 'linux'
          - os: 'macos-latest'
            name: 'macOS ARM'
            version: 'macos-arm'
          - os: 'macos-13'
            name: 'macOS x86-64'
            version: 'macos-x64'
          - os: 'windows-latest'
            name: 'Windows'
            version: 'windows'

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: cargo build --release --verbose
# TODO: Uncomment if/when tests are written
#     - name: Run tests
#       run: cargo test --verbose
      - name: Upload build [macOS/Linux]
        uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: gamecube-uat-bridge-${{ version }}
          file: target/release/gamecube-uat-bridge
      - name: Upload build [Windows]
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: gamecube-uat-bridge-${{ version }}.exe
          file: target/release/gamecube-uat-bridge.exe
